/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   ft_split.c                                         :+:    :+:            */
/*                                                     +:+                    */
/*   By: anagutie <anagutie@student.codam.nl>         +#+                     */
/*                                                   +#+                      */
/*   Created: 2023/10/22 19:08:06 by anagutie      #+#    #+#                 */
/*   Updated: 2023/10/29 13:05:25 by anagutie      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "libft.h"

//This function iterates trougth my string to find the amount 
//of words that will be generated by my split function
static int	free_mem(char **big, int i)
{
	if(big == NULL)
		return(0);
	while (i >= 0)
	{
		free(big[i]);
		i--;
	}
	free(big);
	return (0);

}

static int	count_words(const char *s, char c)
{
	int	i;
	int	times_word;

	i = 0;
	times_word = 0;
	if (s[0] != c)
		times_word++;
	while (s[i + 1 ] != '\0')
	{
		if (s[i] == c && s[i + 1] != c)
			times_word++;
		i++;
	}
	return (times_word);
}

static int	copy_words(char **big, const char *s, char c, int c_w)
{
	int	start;
	int	total;
	int	current_str;

	start = 0;
	current_str = 0;
	while (s[start] && c_w > 0)
	{
		total = 0;
		if (s[start] == c)
			start++;
		if (s[start] != c)
		{
			while (s[start + total] != c && s[start + total] != '\0')
				total++;
			big[current_str] = ft_substr(s, start, total);
			if (big[current_str] == NULL)
				{
					free_mem(big, current_str);
					return(0);
				}
			current_str++;
			start += total;
			c_w--;
		}
	}
	return (1);
}

char	**ft_split(char const *s, char c)
{
	char	**big;

	if (ft_strlen(s) == 0)
		big = ft_calloc(sizeof(char *), 1);
	else
		big = ft_calloc(sizeof(char*), (count_words(s, c) + 1));
	if (big == NULL)
		return (NULL);
	if (copy_words(big, s, c, count_words(s, c)) == 1)
			return (big);
	else
		return (NULL);
}

// int	main(void)
// {
// 	char *str;
// 	char c;
// 	char **result;
// 	int i;

// 	str = "  tripouille  42  ";
// 	c = ' ';
// 	result = ft_split(str, c);
// 	i = 0;

// 	while(result[i])
// 	{
// 		printf("len:%lu\n", strlen(result[i]));
// 		printf(">%s\n",result[i]);
// 		i++;
// 	}
//}